### ISSUE TITLE
No option to make ARA downgrade gracefully when database access fails

### ISSUE THREAD

**Issue by ssbarnea** [dmsimard/ara-archive#128]
I observed that by putting invalid database configuration into ARA_DATABASE, ansible will fail quickly when run.

As a CI user, in order to avoid breaking builds due to temporary glitches regarding database availability I prefer to only display a warning when database access fails instead of having a fatal warning.

This is what I call graceful downgrade of the service, where is better not to record the logs than failing the execution of the build.

Because other users may want different behavior I think that the best is if we can control this via a configuration item and/or environment variable.

Just to be clear: this is a blocker issue for integrating ARA into [infrared](https://github.com/redhat-openstack/infrared) as we cannot afford to build failures.

**Comment by dmsimard** [comment]
This was already discussed in https://github.com/dmsimard/ara/issues/128 -- while ARA can likely be better at catching exceptions, Ansible should *never* let a callback fail or hang the playbook run and I created an issue upstream for that.

Closing this as it's already tracked in https://storyboard.openstack.org/#!/story/2001145
